<?php
/**
 * 2FA Setup View
 * Allows users to enable/disable 2FA and view their QR code
 */
$user = $data['user'];
$secret = $data['secret'];
$qrCodeUrl = $data['qrCodeUrl'];
$backupCodes = $data['backupCodes'];
?>
<div class="max-w-4xl mx-auto p-6">
    <div class="bg-white dark:bg-slate-800 rounded-2xl shadow-xl overflow-hidden border border-slate-200 dark:border-slate-700">
        <div class="p-8 border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50">
            <h1 class="text-3xl font-bold text-slate-900 dark:text-white mb-2">Two-Factor Authentication (2FA)</h1>
            <p class="text-slate-500 dark:text-slate-400">Enhance your account security by adding an extra layer of verification.</p>
        </div>

        <div class="p-8">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-12">
                <!-- Step 1: Secure Device -->
                <div class="space-y-6">
                    <div class="flex items-center gap-4">
                        <span class="flex-shrink-0 w-10 h-10 flex items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 font-bold text-lg">1</span>
                        <h2 class="text-xl font-semibold text-slate-900 dark:text-white">Scan QR Code</h2>
                    </div>
                    <p class="text-slate-600 dark:text-slate-400 leading-relaxed">
                        Scan this QR code with your authenticator app (like Google Authenticator, Microsoft Authenticator, or Authy).
                    </p>
                    <div class="flex justify-center p-4 bg-white rounded-xl shadow-inner border border-slate-100">
                        <img src="<?php echo $qrCodeUrl; ?>" alt="2FA QR Code" class="w-48 h-48">
                    </div>
                    <div class="p-4 bg-slate-50 dark:bg-slate-900/30 rounded-lg border border-slate-200 dark:border-slate-700">
                        <p class="text-xs text-slate-500 uppercase font-bold mb-1 tracking-wider">Manual Secret Key</p>
                        <code class="text-blue-600 dark:text-blue-400 font-mono break-all"><?php echo $secret; ?></code>
                    </div>
                </div>

                <!-- Step 2: Confirmation -->
                <div class="space-y-6">
                    <div class="flex items-center gap-4">
                        <span class="flex-shrink-0 w-10 h-10 flex items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 font-bold text-lg">2</span>
                        <h2 class="text-xl font-semibold text-slate-900 dark:text-white">Verify Setup</h2>
                    </div>
                    <p class="text-slate-600 dark:text-slate-400 mb-4">
                        Enter the 6-digit code generated by your app to confirm enrollment.
                    </p>
                    <form action="/auth/2fa/verify" method="POST" class="space-y-4">
                        <input type="hidden" name="csrf_token" value="<?php echo \App\Core\Security::getCSRFToken(); ?>">
                        <input type="hidden" name="secret" value="<?php echo $secret; ?>">
                        
                        <div>
                            <input type="text" name="code" placeholder="000000" maxlength="6" 
                                   class="w-full text-center text-3xl tracking-[0.5em] font-mono p-4 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500 transition-all outline-none" required>
                        </div>
                        
                        <button type="submit" class="w-full py-4 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl shadow-lg shadow-blue-500/20 transform transition-transform active:scale-95">
                            Verify And Activate
                        </button>
                    </form>

                    <div class="pt-6 border-t border-slate-200 dark:border-slate-700">
                        <h3 class="font-semibold text-slate-900 dark:text-white mb-2 flex items-center gap-2">
                            <svg class="w-5 h-5 text-amber-500" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path></svg>
                            Save Your Backup Codes
                        </h3>
                        <p class="text-sm text-slate-500 dark:text-slate-400 mb-4">
                            If you lose access to your device, these codes are the only way to recover your account.
                        </p>
                        <div class="grid grid-cols-2 gap-2">
                            <?php foreach($backupCodes as $code): ?>
                                <span class="p-2 bg-slate-100 dark:bg-slate-900 text-slate-700 dark:text-slate-300 font-mono text-center rounded border border-slate-200 dark:border-slate-800"><?php echo $code; ?></span>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
